config/routes.rb
SampleContacts::Application.routes.draw do
  resources :contacts
  root :to => 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :email, :first_name, :second_name, :site, :telephone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :second_name %><br />
    <%= f.text_field :second_name %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.telephone_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :site %><br />
    <%= f.url_field :site %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<div class=outlineborder>
<table class="databrouser" border="2">
  <tr class="one">
    <td >First name</td>
    <td>Second name</td>
    <td>Telephone</td>
    <td>Email</td>
    <th>Site</th>
    <td>Address</td>
    <td class="empty"></td>
  </tr>

<% @contacts.each do |contact| %>
  <tr class="two">
    <td><%= contact.first_name %></td>
    <td><%= contact.second_name %></td>
    <td><%= contact.telephone %></td>
    <td><%= contact.email %></td>
    <td><%= contact.site %></td>
    <td><%= contact.address %></td>
    <td class="empty"><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<%= form_for(@contact) do |f| %>
    <tr class="three">        
 
          <td class="set" >
           <%= f.text_field :first_name, :size => 14 %>
          </td>
          <td>
            <%= f.text_field :second_name, :size => 12 %>  
          </td>
          <td>
              <%= f.telephone_field :telephone, :size => 12 %>
          </td>
          <td>
              <%= f.email_field :email, :size => 12 %>
          </td>
          <td>
              <%= f.url_field :site, :size => 12 %>
          </td>
          <td>
        <%= f.text_field :address, :size => 12 %>
          </td>
          <td class="empty">
            <%= f.submit %>
          </td>
        
    </tr>
<% end %>

</table>



</div>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Second name:</b>
  <%= @contact.second_name %>
</p>

<p>
  <b>Telephone:</b>
  <%= @contact.telephone %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Site:</b>
  <%= @contact.site %>
</p>

<p>
  <b>Address:</b>
  <%= @contact.address %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleContacts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>